In [44]:
#library imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.model_selection import train_test_split

In [45]:
#importing data
train = pd.read_csv("train.csv")

In [46]:
#Data Preparation
data = train[['Pclass', 'Sex', 'Age', 'Fare']]

#convert women and men to 1's and 0's
data['Sex'] = data['Sex'].map({'female': 1, 'male': 0})

#take out NULL in Age
data['Age'] = data['Age'].fillna(30)

#take out NULL in Embarked
data['Fare'] = data['Fare'].fillna(8.05)

X = data[['Pclass', 'Sex', 'Age', 'Fare']]
Y = train['Survived']

c:\users\john murphy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
c:\users\john murphy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
c:\users\john murphy\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .lo

In [47]:
#Linear
linear_model = svm.SVC(kernel = 'linear')
linear_model.fit(X, Y)
linear_folds = sklearn.model_selection.cross_val_score(linear_model, X, Y, cv = 5, scoring= 'accuracy')
print(linear_folds)

[0.80446927 0.80337079 0.78651685 0.75280899 0.78651685]


In [48]:
#Quadratic
quad_model = svm.SVC(kernel = 'poly', degree = 2)
quad_model.fit(X, Y)
quad_folds = sklearn.model_selection.cross_val_score(quad_model, X, Y, cv = 5, scoring= 'accuracy')
print(quad_folds)

[0.60335196 0.70786517 0.65730337 0.66292135 0.68539326]


In [49]:
#RBF
RBF_model = svm.SVC(kernel = 'rbf')
RBF_model.fit(X, Y)
RBF_folds = sklearn.model_selection.cross_val_score(RBF_model, X, Y, cv = 5, scoring= 'accuracy')
print(RBF_folds)

[0.5698324  0.71348315 0.69101124 0.68539326 0.69101124]
